### PR TITLE
Allow configuration for behavior about deleting translations

### PR DESCRIPTION
**Pull request by cebe**
- Allow configuration of afterDelete event 
- implement $restrictDeletion property, to prevent deletion of records with multiple translations

default behavior does not change, it just go more flexible by allowing more configuration.

### CODE REVIEW

**Comment by tonydspaniard** [comment]
Thanks @cebe

**Comment by cebe** [comment]
@tonydspaniard could you also please create an 1.0.5 release?

**Comment by tonydspaniard** [comment]
Not at the computer. As soon I am there I will my friend.

**Comment by tonydspaniard** [comment]
I think `1.1.0` @cebe doing it.

**Pull request merged**
