### PR TITLE
After delete event for delete translations

### PR DESCRIPTION
**Pull request by mrstroz**
Hi @2amigos 

I added new event (EVENT_AFTER_DELETE) which delete translations.

Could you check it ?

Do you think it's more safe to leave translations undeleted ?

### CODE REVIEW

**Comment by tonydspaniard** [comment]
@mrstroz I think is fine to remove it, nevertheless, wouldn't be better to have a unique SQL and execute it?

**Comment by tonydspaniard** [comment]
I'll merge it

**Comment by mrstroz** [comment]
@tonydspaniard Could you create 1.2.x or 1.3 release from latest marges ?

**Comment by tonydspaniard** [comment]
@mrstroz sure

**Comment by tonydspaniard** [comment]
@mrstroz done

**Comment by mrstroz** [comment]
Thanks ! :)

**Pull request merged**
